In [1]:
import numpy as np
import pandas as pd
import pandas_profiling as pp

import warnings
warnings.filterwarnings('ignore')

from geopy.distance import geodesic

df = pd.read_csv("data_hackathon_v04.csv", sep="|", parse_dates=["created_at"], index_col="ride_id")

In [2]:
from h3 import h3

df["cell_id"] = df[["pickup_lat","pickup_lng"]].apply(lambda x: h3.geo_to_h3(*x, 7), axis=1)

In [3]:
def make_df_time(df):
    df_time = df[["created_at"]]

    df_time["day"] = df_time.created_at.dt.day
    df_time["month"] = df_time.created_at.dt.month
    df_time["year"] = df_time.created_at.dt.year
    df_time["is_year_start"] = np.int8(df_time.created_at.dt.is_year_start)
    df_time["is_year_end"] = np.int8(df_time.created_at.dt.is_year_end)
    df_time["dayofyear"] = df_time.created_at.dt.dayofyear
    df_time["dayofweek"] = df_time.created_at.dt.dayofweek

    df_time["week"] = df_time.created_at.dt.week

    df_time["hour"] = df_time.created_at.dt.hour
    df_time["minute"] = df_time.created_at.dt.minute
    df_time["final_time"] = (df_time["hour"] + df_time["minute"] // 30) % 24
    df_time["dayofweek"] = df_time.created_at.dt.dayofweek
    df_time["is_weekend"] = df_time["dayofweek"] // 5

    df_time.drop(["created_at"], inplace=True, axis=1)
    return df_time

def in_square(x, y):
    square = (49.895468, 23.907734, 49.769849, 24.121698)
    return (square[2] <= x <= square[0]) and (square[1] <= y <= square[3])

def clear_df(df):
    df["in_Lviv"] = (df[["pickup_lat", "pickup_lng"]].apply(lambda x: in_square(*x), axis=1) & df[["dropoff_lat", "dropoff_lng"]].apply(lambda x: in_square(*x), axis=1))
    df = df[df["in_Lviv"]]
    df["simple_distance"] = np.array(list(map(lambda x: geodesic(x[:2], x[2:]).km, 
                                          df[["pickup_lat", "pickup_lng", "dropoff_lat", "dropoff_lng"]].values)))
    df = df[abs(df["simple_distance"] - df["ride_distance"]) < 10]
    df.drop(["in_Lviv", "simple_distance"], axis=1, inplace=True)
    return df

def add_agg(df_in, df_out, group_by, name, aggs, add_name):
    if "mode" in aggs:
        aggs.remove("mode")
        _ = df_in.groupby(group_by)[name].agg(aggs)
        _["mode"] = df_in.groupby(group_by)[name].apply(lambda x: np.bincount(x).argmax())
    else:
        _ = df_in.groupby(group_by)[name].agg(aggs)
    _.columns = ["_".join([add_name, group_by, name, column]) for column in _.columns]
    return df_out.merge(_, left_index=True, right_index=True, how="left")

def make_aggs(df, name, days, LAST_DAY):
    df__ = pd.DataFrame(index=df[name].unique())

    df_ = df[(LAST_DAY - df.created_at).dt.days > 0]
    df__ = add_agg(df_, df__, name, "canceled_by_client", ["mean", "median", "std", "count"], "all")
    df__ = df__[df__[f"all_{name}_canceled_by_client_count"] > days]
    df__ = add_agg(df_, df__, name, "canceled_by_driver", ["mean", "median", "std"], "all")
    df__ = add_agg(df_, df__, name, "ride_to_suburb", ["mean", "std"], "all")
    df__ = add_agg(df_, df__, name, 'ride_distance', ["mean", "std", "median", "min", "max"], "all")
    df__ = add_agg(df_, df__, name, 'dayofweek', ["median", "mode"], "all")
    df__ = add_agg(df_, df__, name, 'final_time', ["median", "mode"], "all")
    df__ = add_agg(df_, df__, name, 'is_weekend', ["median", "std", "mean", "mode"], "all")
    
    df_ = df[(LAST_DAY - df.created_at).dt.days // 8 == 0]
    df__ = add_agg(df_, df__, name, "canceled_by_client", ["mean", "median", "std", "count"], "3_month")
    df__ = add_agg(df_, df__, name, "canceled_by_driver", ["mean", "median", "std"], "3_month")
    df__ = add_agg(df_, df__, name, "ride_to_suburb", ["mean", "std"], "3_month")
    df__ = add_agg(df_, df__, name, 'ride_distance', ["mean", "std", "median", "min", "max"], "3_month")
    df__ = add_agg(df_, df__, name, 'dayofweek', ["median", "mode"], "3_month")
    df__ = add_agg(df_, df__, name, 'final_time', ["median", "mode"], "3_month")
    df__ = add_agg(df_, df__, name, 'is_weekend', ["median", "std", "mean", "mode"], "3_month")

    df_ = df[(LAST_DAY - df.created_at).dt.days // 6 == 0]
    df__ = add_agg(df_, df__, name, "canceled_by_client", ["mean", "median", "std", "count"], "3_month")
    df__ = add_agg(df_, df__, name, "canceled_by_driver", ["mean", "median", "std"], "3_month")
    df__ = add_agg(df_, df__, name, "ride_to_suburb", ["mean", "std"], "3_month")
    df__ = add_agg(df_, df__, name, 'ride_distance', ["mean", "std", "median", "min", "max"], "3_month")
    df__ = add_agg(df_, df__, name, 'dayofweek', ["median", "mode"], "3_month")
    df__ = add_agg(df_, df__, name, 'final_time', ["median", "mode"], "3_month")
    df__ = add_agg(df_, df__, name, 'is_weekend', ["median", "std", "mean", "mode"], "3_month")

    df_ = df[(LAST_DAY - df.created_at).dt.days // 4 == 0]
    df__ = add_agg(df_, df__, name, "canceled_by_client", ["mean", "median", "std", "count"], "month")
    df__ = add_agg(df_, df__, name, "canceled_by_driver", ["mean", "median", "std"], "month")
    df__ = add_agg(df_, df__, name, "ride_to_suburb", ["mean", "std"], "month")
    df__ = add_agg(df_, df__, name, 'ride_distance', ["mean", "std", "median", "min", "max"], "month")
    df__ = add_agg(df_, df__, name, 'dayofweek', ["median", "mode"], "month")
    df__ = add_agg(df_, df__, name, 'final_time', ["median", "mode"], "month")
    df__ = add_agg(df_, df__, name, 'is_weekend', ["median", "std", "mean", "mode"], "month")
    df__[f"{name}_active"] = df__.index.isin(df_[name])

    df_ = df[(LAST_DAY - df.created_at).dt.days // 3 == 0]
    df__ = add_agg(df_, df__, name, "canceled_by_client", ["mean", "median", "std", "count"], "week")
    df__ = add_agg(df_, df__, name, "canceled_by_driver", ["mean", "median", "std"], "week")
    df__ = add_agg(df_, df__, name, "ride_to_suburb", ["mean", "std"], "week")
    df__ = add_agg(df_, df__, name, 'ride_distance', ["mean", "std", "median", "min", "max"], "week")
    df__ = add_agg(df_, df__, name, 'dayofweek', ["median", "mode"], "week")
    df__ = add_agg(df_, df__, name, 'final_time', ["median", "mode"], "week")
    df__ = add_agg(df_, df__, name, 'is_weekend', ["median", "std", "mean", "mode"], "week")

    df_ = df[(LAST_DAY - df.created_at).dt.days // 2 == 0]
    df__ = add_agg(df_, df__, name, "canceled_by_client", ["mean", "median", "std", "count"], "day")
    df__ = add_agg(df_, df__, name, "canceled_by_driver", ["mean", "median", "std"], "day")
    df__ = add_agg(df_, df__, name, "ride_to_suburb", ["mean", "std"], "day")
    df__ = add_agg(df_, df__, name, 'ride_distance', ["mean", "std", "median", "min", "max"], "day")
    df__ = add_agg(df_, df__, name, 'dayofweek', ["median", "mode"], "day")
    df__ = add_agg(df_, df__, name, 'final_time', ["median", "mode"], "day")
    df__ = add_agg(df_, df__, name, 'is_weekend', ["median", "std", "mean", "mode"], "day")
    print(df__.shape)
    df__.fillna(0.0, inplace=True)
    return df__

In [4]:
%%time
df = clear_df(df)

LAST_DAY = df.created_at.max()
LAST_DAY

CPU times: user 3min 23s, sys: 208 ms, total: 3min 24s
Wall time: 3min 24s


In [5]:
%%time
df_time = make_df_time(df)
df = df.merge(df_time, how="left", left_index=True, right_index=True)

CPU times: user 1.02 s, sys: 88 ms, total: 1.11 s
Wall time: 1.1 s


In [6]:
# %%time
# df_driver = make_aggs(df, "driver_id", 30)
# %%time
# df_user = make_aggs(df, "user_id", 10)
# df = df.merge(df_driver, how="left", left_on="driver_id", right_index=True)
# df = df.merge(df_user, how="left", left_on="user_id", right_index=True)

In [7]:
df.dropna(0, inplace=True)
df_cell = make_aggs(df, "cell_id", 26, LAST_DAY)
df = df[df.cell_id.isin(df_cell.index)]
df.to_csv("new_csv.csv")
df_cell

(43, 133)


all_cell_id_canceled_by_client_mean  \
871e7689cffffff                             0.041075   
871e76882ffffff                             0.033453   
871e7689dffffff                             0.040810   
871e768b3ffffff                             0.062723   
871e7689bffffff                             0.032218   
871e76126ffffff                             0.038239   
871e76883ffffff                             0.049001   
871e76895ffffff                             0.039155   
871e76898ffffff                             0.034685   
871e76880ffffff                             0.031094   
871e76899ffffff                             0.032355   
871e76881ffffff                             0.035518   
871e7689affffff                             0.028620   
871e76124ffffff                             0.037164   
871e76134ffffff                             0.040909   
871e7689effffff                             0.033607   
871e76891ffffff                             0.035660   
871e76890ffffff                             0.039761   
871e76135ffffff                             0.035242   
871e76893ffffff                             0.038975   
871e7688affffff                             0.040324   
871e7688effffff                             0.042849   
871e76885ffffff                             0.040628   
871e76896ffffff                             0.031439   
871e76c69ffffff                             0.056075   
871e76892ffffff                             0.057922   
871e76c6dffffff                             0.029706   
871e768aaffffff                             0.052870   
871e7688cffffff                             0.041045   
871e76888ffffff                             0.054376   
871e76886ffffff                             0.069376   
871e768abffffff                             0.078818   
871e76122ffffff                             0.056980   
871e76c68ffffff                             0.093851   
871e76894ffffff                             0.061475   
871e768b1ffffff                             0.047445   
871e76c6cffffff                             0.074866   
871e768a8ffffff                             0.095890   
871e7688bffffff                             0.048780   
871e768b0ffffff                             0.050209   
871e76125ffffff                             0.064516   
871e76884ffffff                             0.096774   
871e76889ffffff                             0.159091   

                 all_cell_id_canceled_by_client_median  \
871e7689cffffff                                      0   
871e76882ffffff                                      0   
871e7689dffffff                                      0   
871e768b3ffffff                                      0   
871e7689bffffff                                      0   
871e76126ffffff                                      0   
871e76883ffffff                                      0   
871e76895ffffff                                      0   
871e76898ffffff                                      0   
871e76880ffffff                                      0   
871e76899ffffff                                      0   
871e76881ffffff                                      0   
871e7689affffff                                      0   
871e76124ffffff                                      0   
871e76134ffffff                                      0   
871e7689effffff                                      0   
871e76891ffffff                                      0   
871e76890ffffff                                      0   
871e76135ffffff                                      0   
871e76893ffffff                                      0   
871e7688affffff                                      0   
871e7688effffff                                      0   
871e76885ffffff                                      0   
871e76896ffffff                                      0   
871e76c69ffffff                                      0   
871e76892ffffff                             

In [8]:
df_cell["all_cell_id_canceled_by_client_count"]

871e7689cffffff    100717
871e76882ffffff     67707
871e7689dffffff     76452
871e768b3ffffff      3651
871e7689bffffff     26383
871e76126ffffff     19012
871e76883ffffff    236483
871e76895ffffff      8428
871e76898ffffff     35606
871e76880ffffff     42195
871e76899ffffff     33689
871e76881ffffff     37953
871e7689affffff     33927
871e76124ffffff      2906
871e76134ffffff     12760
871e7689effffff     85399
871e76891ffffff     43746
871e76890ffffff      4678
871e76135ffffff      7406
871e76893ffffff     15215
871e7688affffff     16888
871e7688effffff     18577
871e76885ffffff      6301
871e76896ffffff       827
871e76c69ffffff       856
871e76892ffffff      2348
871e76c6dffffff      3400
871e768aaffffff      3310
871e7688cffffff       536
871e76888ffffff      1931
871e76886ffffff      1009
871e768abffffff       406
871e76122ffffff       351
871e76c68ffffff       309
871e76894ffffff       244
871e768b1ffffff       274
871e76c6cffffff       187
871e768a8ffffff        73
871e7688bfff

In [9]:
df.shape

(957478, 24)

In [10]:
center = list(df_cell.index)
center_size = len(center)

In [11]:
df_ = df[df["cell_id"].isin(center)]

In [12]:
from datetime import timedelta

from keras.utils import to_categorical

Using TensorFlow backend.


In [13]:
day = LAST_DAY.date()
day = day - timedelta(0)

In [22]:
day_nums = 30
X = []
y = np.zeros((24, day_nums, center_size))
for k in range(0, day_nums):
    day = LAST_DAY.date() - timedelta(k + 22)
    redundant_cols=["hour", "minute", "final_time"]

    df__time = make_df_time(pd.DataFrame({"created_at": [pd.Timestamp(day)]}))
    df__time.drop(redundant_cols, axis=1, inplace=True)
    df__time = np.int16(np.concatenate((to_categorical(df__time["month"], 12)[0],
                   to_categorical(df__time["dayofweek"], 7)[0],
                   df__time.drop(["month", "dayofweek"], axis=1).values[0])))
    
    
    res = make_aggs(df_, "cell_id", 0, day).values.reshape(1, -1)[0]
    X.append(np.concatenate((df__time, res)).reshape(1, -1))
    
    group = df_[df_.created_at.dt.date == day].groupby(["final_time", "cell_id"]).created_at.count()
    for i in range(24):
        for j, cell in enumerate(center):
            if i in group:
                if cell in group.loc[i]:
                    y[i][k][j] = group.loc[i, cell]

(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)
(43, 133)


In [23]:
X = np.array(X)
X.shape

(30, 1, 5745)

In [24]:
y.shape

(24, 30, 43)

In [25]:
from keras.layers import Dense, Flatten, LSTM, Input, BatchNormalization, Dropout
from keras.models import Model
import keras.backend as K 

In [46]:
inp = Input(tuple(X.shape[1:]))
lstm1 = LSTM(units=128, activation="relu", return_sequences=True)(inp)
# lstm2 = LSTM(units=128, activation="relu", return_sequences=True)(lstm1)
outs= []
for i in range(y.shape[0]):
    flt = Flatten()(lstm1)
    dns = Dense(units=128, activation="relu")(flt)
    bn = BatchNormalization()(dns)
    outs.append(Dense(center_size, activation="relu")(bn))
model = Model(inp, outs)

In [47]:
model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_5 (InputLayer)            (None, 1, 5745)      0                                            
__________________________________________________________________________________________________
lstm_7 (LSTM)                   (None, 1, 128)       3007488     input_5[0][0]                    
__________________________________________________________________________________________________
flatten_97 (Flatten)            (None, 128)          0           lstm_7[0][0]                     
__________________________________________________________________________________________________
flatten_98 (Flatten)            (None, 128)          0           lstm_7[0][0]                     
__________________________________________________________________________________________________
flatten_99

In [48]:
from keras.metrics import mean_squared_logarithmic_error

In [ ]:
model = Model(inp, outs)
def rmsle(y_true, y_pred):
        return K.sqrt(K.mean(K.square(K.log(y_pred + 1.) - K.log(y_true + 1.)), axis=-1)) 

model.compile(optimizer = "adam", loss = mean_squared_logarithmic_error, metrics =["accuracy"])

In [ ]:
model.fit(X, list(y), batch_size=2, epochs=10000)

Epoch 1/10000
30/30 [==============================] - 19s 626ms/step - loss: 49.7594 - dense_194_loss: 2.2443 - dense_196_loss: 1.7175 - dense_198_loss: 1.3085 - dense_200_loss: 0.8866 - dense_202_loss: 0.7293 - dense_204_loss: 0.9202 - dense_206_loss: 0.8346 - dense_208_loss: 0.9751 - dense_210_loss: 2.1409 - dense_212_loss: 2.8631 - dense_214_loss: 2.9755 - dense_216_loss: 2.6277 - dense_218_loss: 2.1128 - dense_220_loss: 2.0660 - dense_222_loss: 2.1180 - dense_224_loss: 2.1448 - dense_226_loss: 2.3068 - dense_228_loss: 2.5740 - dense_230_loss: 2.9851 - dense_232_loss: 2.8780 - dense_234_loss: 2.6863 - dense_236_loss: 2.4457 - dense_238_loss: 2.6098 - dense_240_loss: 2.6089 - dense_194_acc: 0.0000e+00 - dense_196_acc: 0.0000e+00 - dense_198_acc: 0.0000e+00 - dense_200_acc: 0.4000 - dense_202_acc: 0.0000e+00 - dense_204_acc: 0.0000e+00 - dense_206_acc: 0.1333 - dense_208_acc: 0.0000e+00 - dense_210_acc: 0.1667 - dense_212_acc: 0.0000e+00 - dense_214_acc: 0.0000e+00 - dense_216_acc: 0

30/30 [==============================] - 1s 49ms/step - loss: 37.0116 - dense_194_loss: 1.6787 - dense_196_loss: 1.2638 - dense_198_loss: 0.9963 - dense_200_loss: 0.6931 - dense_202_loss: 0.6046 - dense_204_loss: 0.6912 - dense_206_loss: 0.6388 - dense_208_loss: 0.6901 - dense_210_loss: 1.5661 - dense_212_loss: 2.0908 - dense_214_loss: 2.2125 - dense_216_loss: 1.9442 - dense_218_loss: 1.5251 - dense_220_loss: 1.5918 - dense_222_loss: 1.5396 - dense_224_loss: 1.5698 - dense_226_loss: 1.6901 - dense_228_loss: 1.8777 - dense_230_loss: 2.2242 - dense_232_loss: 2.1915 - dense_234_loss: 2.0186 - dense_236_loss: 1.8506 - dense_238_loss: 1.9283 - dense_240_loss: 1.9341 - dense_194_acc: 0.0333 - dense_196_acc: 0.1000 - dense_198_acc: 0.5000 - dense_200_acc: 0.5000 - dense_202_acc: 0.4667 - dense_204_acc: 0.4000 - dense_206_acc: 0.3667 - dense_208_acc: 0.0667 - dense_210_acc: 0.2667 - dense_212_acc: 0.1333 - dense_214_acc: 0.1667 - dense_216_acc: 0.0333 - dense_218_acc: 0.4667 - dense_220_acc: 0

30/30 [==============================] - 1s 41ms/step - loss: 34.1875 - dense_194_loss: 1.5093 - dense_196_loss: 1.1801 - dense_198_loss: 0.9118 - dense_200_loss: 0.6578 - dense_202_loss: 0.5956 - dense_204_loss: 0.5525 - dense_206_loss: 0.5840 - dense_208_loss: 0.6458 - dense_210_loss: 1.4066 - dense_212_loss: 1.9299 - dense_214_loss: 2.0539 - dense_216_loss: 1.7701 - dense_218_loss: 1.4099 - dense_220_loss: 1.4398 - dense_222_loss: 1.4452 - dense_224_loss: 1.4870 - dense_226_loss: 1.5822 - dense_228_loss: 1.7574 - dense_230_loss: 2.0705 - dense_232_loss: 2.0251 - dense_234_loss: 1.8592 - dense_236_loss: 1.7293 - dense_238_loss: 1.7966 - dense_240_loss: 1.7878 - dense_194_acc: 0.4000 - dense_196_acc: 0.0333 - dense_198_acc: 0.5000 - dense_200_acc: 0.4667 - dense_202_acc: 0.4667 - dense_204_acc: 0.3667 - dense_206_acc: 0.5000 - dense_208_acc: 0.2000 - dense_210_acc: 0.1667 - dense_212_acc: 0.1667 - dense_214_acc: 0.1000 - dense_216_acc: 0.1667 - dense_218_acc: 0.5000 - dense_220_acc: 0

30/30 [==============================] - 1s 40ms/step - loss: 32.8764 - dense_194_loss: 1.4193 - dense_196_loss: 1.1563 - dense_198_loss: 0.8846 - dense_200_loss: 0.6592 - dense_202_loss: 0.5738 - dense_204_loss: 0.2802 - dense_206_loss: 0.5604 - dense_208_loss: 0.6440 - dense_210_loss: 1.3568 - dense_212_loss: 1.8878 - dense_214_loss: 1.9531 - dense_216_loss: 1.6936 - dense_218_loss: 1.3947 - dense_220_loss: 1.4182 - dense_222_loss: 1.3919 - dense_224_loss: 1.4381 - dense_226_loss: 1.5320 - dense_228_loss: 1.6891 - dense_230_loss: 2.0102 - dense_232_loss: 1.9700 - dense_234_loss: 1.7987 - dense_236_loss: 1.6646 - dense_238_loss: 1.7663 - dense_240_loss: 1.7337 - dense_194_acc: 0.5000 - dense_196_acc: 0.4333 - dense_198_acc: 0.5000 - dense_200_acc: 0.4667 - dense_202_acc: 0.4667 - dense_204_acc: 0.5333 - dense_206_acc: 0.6333 - dense_208_acc: 0.3333 - dense_210_acc: 0.2333 - dense_212_acc: 0.3333 - dense_214_acc: 0.1333 - dense_216_acc: 0.3333 - dense_218_acc: 0.5000 - dense_220_acc: 0

30/30 [==============================] - 1s 45ms/step - loss: 32.1296 - dense_194_loss: 1.3642 - dense_196_loss: 1.1228 - dense_198_loss: 0.8230 - dense_200_loss: 0.6342 - dense_202_loss: 0.5521 - dense_204_loss: 0.2528 - dense_206_loss: 0.5529 - dense_208_loss: 0.6314 - dense_210_loss: 1.2889 - dense_212_loss: 1.8660 - dense_214_loss: 1.9092 - dense_216_loss: 1.6916 - dense_218_loss: 1.3850 - dense_220_loss: 1.4153 - dense_222_loss: 1.3391 - dense_224_loss: 1.4500 - dense_226_loss: 1.4913 - dense_228_loss: 1.6629 - dense_230_loss: 1.9597 - dense_232_loss: 1.9132 - dense_234_loss: 1.7630 - dense_236_loss: 1.6401 - dense_238_loss: 1.7340 - dense_240_loss: 1.6868 - dense_194_acc: 0.5000 - dense_196_acc: 0.5000 - dense_198_acc: 0.5000 - dense_200_acc: 0.4667 - dense_202_acc: 0.4667 - dense_204_acc: 0.8333 - dense_206_acc: 0.6333 - dense_208_acc: 0.3667 - dense_210_acc: 0.2000 - dense_212_acc: 0.3000 - dense_214_acc: 0.2000 - dense_216_acc: 0.3667 - dense_218_acc: 0.4667 - dense_220_acc: 0

30/30 [==============================] - 1s 37ms/step - loss: 31.4911 - dense_194_loss: 1.0486 - dense_196_loss: 1.1252 - dense_198_loss: 0.8137 - dense_200_loss: 0.6390 - dense_202_loss: 0.5500 - dense_204_loss: 0.2344 - dense_206_loss: 0.5699 - dense_208_loss: 0.6388 - dense_210_loss: 1.2894 - dense_212_loss: 1.8533 - dense_214_loss: 1.8958 - dense_216_loss: 1.6557 - dense_218_loss: 1.3485 - dense_220_loss: 1.3754 - dense_222_loss: 1.3640 - dense_224_loss: 1.4097 - dense_226_loss: 1.5055 - dense_228_loss: 1.6794 - dense_230_loss: 1.9371 - dense_232_loss: 1.8547 - dense_234_loss: 1.7253 - dense_236_loss: 1.6071 - dense_238_loss: 1.6961 - dense_240_loss: 1.6746 - dense_194_acc: 0.5000 - dense_196_acc: 0.5000 - dense_198_acc: 0.5000 - dense_200_acc: 0.4667 - dense_202_acc: 0.4667 - dense_204_acc: 0.8333 - dense_206_acc: 0.5667 - dense_208_acc: 0.3333 - dense_210_acc: 0.2000 - dense_212_acc: 0.2667 - dense_214_acc: 0.1667 - dense_216_acc: 0.3000 - dense_218_acc: 0.5000 - dense_220_acc: 0

30/30 [==============================] - 1s 37ms/step - loss: 29.9881 - dense_194_loss: 0.4016 - dense_196_loss: 1.1135 - dense_198_loss: 0.8255 - dense_200_loss: 0.6323 - dense_202_loss: 0.5468 - dense_204_loss: 0.2381 - dense_206_loss: 0.5568 - dense_208_loss: 0.6392 - dense_210_loss: 1.2756 - dense_212_loss: 1.8329 - dense_214_loss: 1.9053 - dense_216_loss: 1.6079 - dense_218_loss: 1.3119 - dense_220_loss: 1.3020 - dense_222_loss: 1.3644 - dense_224_loss: 1.3855 - dense_226_loss: 1.4819 - dense_228_loss: 1.6230 - dense_230_loss: 1.4327 - dense_232_loss: 1.8673 - dense_234_loss: 1.7025 - dense_236_loss: 1.5947 - dense_238_loss: 1.7045 - dense_240_loss: 1.6422 - dense_194_acc: 0.5000 - dense_196_acc: 0.5000 - dense_198_acc: 0.5000 - dense_200_acc: 0.4667 - dense_202_acc: 0.4667 - dense_204_acc: 0.8333 - dense_206_acc: 0.5000 - dense_208_acc: 0.4000 - dense_210_acc: 0.1000 - dense_212_acc: 0.2333 - dense_214_acc: 0.2000 - dense_216_acc: 0.3333 - dense_218_acc: 0.4667 - dense_220_acc: 0

30/30 [==============================] - 1s 37ms/step - loss: 24.3305 - dense_194_loss: 0.2736 - dense_196_loss: 1.0729 - dense_198_loss: 0.8130 - dense_200_loss: 0.6405 - dense_202_loss: 0.5150 - dense_204_loss: 0.2109 - dense_206_loss: 0.5549 - dense_208_loss: 0.6215 - dense_210_loss: 1.2226 - dense_212_loss: 1.7651 - dense_214_loss: 1.8561 - dense_216_loss: 0.6269 - dense_218_loss: 0.5372 - dense_220_loss: 1.2207 - dense_222_loss: 1.0495 - dense_224_loss: 1.3483 - dense_226_loss: 1.4674 - dense_228_loss: 1.4573 - dense_230_loss: 0.3596 - dense_232_loss: 1.8286 - dense_234_loss: 1.6610 - dense_236_loss: 1.3229 - dense_238_loss: 1.3093 - dense_240_loss: 0.5955 - dense_194_acc: 0.5000 - dense_196_acc: 0.5000 - dense_198_acc: 0.5000 - dense_200_acc: 0.5000 - dense_202_acc: 0.5000 - dense_204_acc: 0.8333 - dense_206_acc: 0.3667 - dense_208_acc: 0.4667 - dense_210_acc: 0.1333 - dense_212_acc: 0.2667 - dense_214_acc: 0.2333 - dense_216_acc: 0.3333 - dense_218_acc: 0.5000 - dense_220_acc: 0

30/30 [==============================] - 1s 37ms/step - loss: 16.9259 - dense_194_loss: 0.2517 - dense_196_loss: 0.7063 - dense_198_loss: 0.7241 - dense_200_loss: 0.6297 - dense_202_loss: 0.5059 - dense_204_loss: 0.2161 - dense_206_loss: 0.5334 - dense_208_loss: 0.6411 - dense_210_loss: 1.1973 - dense_212_loss: 1.7471 - dense_214_loss: 0.4218 - dense_216_loss: 0.3093 - dense_218_loss: 0.2937 - dense_220_loss: 0.5959 - dense_222_loss: 0.2378 - dense_224_loss: 1.3696 - dense_226_loss: 1.4230 - dense_228_loss: 0.6069 - dense_230_loss: 0.3152 - dense_232_loss: 1.8129 - dense_234_loss: 1.1951 - dense_236_loss: 0.3554 - dense_238_loss: 0.4342 - dense_240_loss: 0.4022 - dense_194_acc: 0.6667 - dense_196_acc: 0.5000 - dense_198_acc: 0.5000 - dense_200_acc: 0.4667 - dense_202_acc: 0.4667 - dense_204_acc: 0.8333 - dense_206_acc: 0.4333 - dense_208_acc: 0.4000 - dense_210_acc: 0.1333 - dense_212_acc: 0.2667 - dense_214_acc: 0.1667 - dense_216_acc: 0.2333 - dense_218_acc: 0.5000 - dense_220_acc: 0

30/30 [==============================] - 1s 37ms/step - loss: 11.3424 - dense_194_loss: 0.2386 - dense_196_loss: 0.4215 - dense_198_loss: 0.6335 - dense_200_loss: 0.6154 - dense_202_loss: 0.4042 - dense_204_loss: 0.2134 - dense_206_loss: 0.4788 - dense_208_loss: 0.5907 - dense_210_loss: 0.3911 - dense_212_loss: 1.7982 - dense_214_loss: 0.3262 - dense_216_loss: 0.2567 - dense_218_loss: 0.2074 - dense_220_loss: 0.2472 - dense_222_loss: 0.2207 - dense_224_loss: 0.3705 - dense_226_loss: 1.3750 - dense_228_loss: 0.2221 - dense_230_loss: 0.2421 - dense_232_loss: 0.8814 - dense_234_loss: 0.4291 - dense_236_loss: 0.2372 - dense_238_loss: 0.2617 - dense_240_loss: 0.2798 - dense_194_acc: 0.6333 - dense_196_acc: 0.5333 - dense_198_acc: 0.5000 - dense_200_acc: 0.4667 - dense_202_acc: 0.5333 - dense_204_acc: 0.8333 - dense_206_acc: 0.4333 - dense_208_acc: 0.4667 - dense_210_acc: 0.1000 - dense_212_acc: 0.2667 - dense_214_acc: 0.2333 - dense_216_acc: 0.2667 - dense_218_acc: 0.4667 - dense_220_acc: 0

In [ ]:
from sklearn.metrics import mean_squared_log_error

In [ ]:
for k in range(0, 21):
    day = LAST_DAY.date() - timedelta(k)
    X = make_aggs(df_[df_.created_at < day], "cell_id", 0, day).values.reshape(1, -1)
    
    y = np.zeros((24, 1, 7))
    group = df_[df_.created_at.dt.date == day].groupby(["final_time", "cell_id"]).created_at.count()
    for i in range(24):
        for j, cell in enumerate(center):
            if i in group:
                if cell in group.loc[i]:
                    y[i][0][j] = group.loc[i, cell]
    print(y)
#     pred = model.predict(np.array([X]))
    

In [427]:
LAST_DAY

Timestamp('2019-02-21 15:59:53.877000')

In [428]:
d

created_at  pickup_lat  \
ride_id                                                                 
0000e61e5282484d943291df7266ee33n 2019-01-18 09:18:44.377   49.837013   
000152b506034bcda66a4a813f1408f4n 2018-12-20 02:28:31.017   49.844044   
0001a52849f141a48f292bbd73b8d7c5n 2018-11-05 22:38:28.870   49.834843   
000218b0c8494514b78a2730c8e546bdn 2018-12-14 07:53:01.270   49.843437   
0002d81308f34226bfd1ed1b59353fd9n 2018-11-02 23:53:50.663   49.840462   
00030efa111e4c50b7d6da117cf4c484n 2018-10-26 21:56:57.693   49.839897   
000506b3923c4703ab4864e16e080736n 2019-01-21 22:50:36.340   49.837749   
000524877c4c4ccba1d16276efb03a22n 2018-09-03 16:19:58.297   49.834614   
000548fdc26e4db3992c7b4f96176511n 2019-01-19 12:17:50.720   49.842392   
0005e690fe824dda99bd4d34e5b932d3n 2018-10-08 23:00:20.520   49.843849   
0005f7f1b72c405d98e0b5e48b094764n 2018-12-02 19:23:32.077   49.846008   
00063b64b09340d5b1a62db389a2eeb5n 2018-11-25 03:55:03.240   49.845276   
0006aed7d9b3470bb13699690ce67079n 2018-11-25 04:30:32.307   49.847485   
0006e6fb445e428baf6bdb20663e79a2n 2018-12-17 20:39:33.480   49.840263   
000726f88ac84128afb87007f9d1a840n 2018-09-18 19:12:31.650   49.833652   
00072f29ed31417c819086cc0b60e42fn 2018-10-27 15:08:42.710   49.837143   
000737847f5c44b99b99345bc8a0c907n 2019-01-12 23:47:07.867   49.837444   
00079eff55014b01bd1cc5bc5350a690n 2018-11-04 08:00:24.700   49.847546   
0007ec9c7c0a4aec8ca3f4cf272dd939n 2018-11-09 01:15:16.687   49.843170   
00088ddc1f29427e8e2ad55e16ce08b0n 2018-09-29 23:44:02.210   49.841545   
000a0d4603d7476489df40d724cfb63dn 2018-12-10 13:58:40.697   49.832191   
000ac924378241db83de5644cc56aa15n 2019-01-25 14:14:59.453   49.838322   
000ba2768e9643aaa2fa21bb5d97e3a4n 2019-01-21 22:37:27.550   49.837189   
000bba09199e4306aaaa09cb3e91f03dn 2019-01-23 22:52:33.520   49.843117   
000bbc4594474d5eb1edb7624385ba95n 2018-09-01 00:43:09.090   49.845207   
000bfc56554e45a48ea7783ec85644d0n 2018-10-12 02:34:20.477   49.829952   
000c3425c04d4fee81b500ce4ea0914an 2018-12-18 06:37:00.763   49.839512   
000cae8685d646c3b84099006ce1804an 2019-01-23 16:19:30.307   49.849503   
000cb29276bf47ce90226f89d6f6ad4bn 2018-12-01 23:43:28.597   49.837772   
000d0284f3a247b981c128cd919d6bb5n 2019-02-20 23:45:33.607   49.839512   
...                                                   ...         ...   
fffc3eacbe504148a208da1a69d36dfbn 2018-12-05 09:59:59.310   49.837013   
fffc48d32fd441438b5af7b6d704135dn 2018-12-07 17:28:18.600   49.834698   
fffc6b77ad4a468faee7f33672108280n 2018-09-10 00:57:28.837   49.837597   
fffc70b71058423799e310d79b971288n 2018-09-07 17:41:43.980   49.845982   
fffc816be24a47669e9242a315542dd6n 2018-12-02 01:48:41.277   49.836853   
fffcbd9a11974a5ea3ac8ddbb5eab959n 2018-10-01 11:14:38.987   49.842552   
fffcd3cfdead469cb37a2218ad21476dn 2019-01-07 18:25:46.610   49.839733   
fffcedff5c9d42fea8a11fe161a79185n 2018-09-30 22:48:21.477   49.841003   
fffd1b555a894a019f5fb6b9d2389511n 2018-11-22 00:22:06.277   49.839825   
fffda0f0776a4ebebaff4fbe672ea0f0n 2018-08-31 17:04:41.807   49.840164   
fffda2db8c5a4e29a0994da077f8b68en 2018-11-11 04:53:55.907   49.843594   
fffde5bd9ec04d41acf007049f9c8318n 2018-12-09 00:46:01.870   49.846680   
fffdf2932c1448979e9ebf3ffb924371n 2018-10-24 22:16:13.023   49.847630   
fffe6c974ad24255af6c7fde7639c64an 2018-10-26 15:35:48.947   49.833717   
fffe7af6cc174ff4a2d3fee1aa3c91b3n 2018-12-22 18:52:02.610   49.843140   
fffe7d71753843f1acc8d5f7bd824077n 2018-12-27 16:25:31.820   49.839890   
fffe9477fa284fdd8bc3755270eee35en 2018-08-31 23:24:55.763   49.842636   
fffea2b28bae4db19490273c2aff7679n 2018-10-03 23:02:42.883   49.837906   
fffeb06df4a74666aa025f53ea2b4164n 2018-11-29 23:32:21.443   49.845554   
fffeb34a82f946dca856e09a940a4668n 2018-10-26 00:51:19.443   49.840099   
fffebc8f0e2d4d83879b837d50abf9f8n 2018-11-16 08:35:49.533   49.835274   
fffec382f74b4f3aa18d1b2cc05688c8n 2018-12-09 14:27:25.470   49.838558   
fffef8cc358e4c18b1d5d0a5f509018b

In [426]:
group = df_[df_.created_at.dt.date == day].groupby(["final_time", "cell_id"]).created_at.count()
group

Series([], Name: created_at, dtype: int64)

In [422]:
pred

[array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([[-0., -0., -0., -0., -0., -0., -0.]], dtype=float32),
 array([

In [423]:
y

array([[[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]]])

In [416]:
mean_squared_logarithmic_error(np.array([1.]), np.array([3.]))

AttributeError: 'numpy.dtype' object has no attribute 'base_dtype'